bot:
  adminId: 213411446
  adminUrl : fry55
  token: 1392424435:AAFWlQHWheZY26S6xCMNXtRyN0E_7-8V6h8
  name: Monopoly
  botUrl: https://t.me/Monetary24bot

server:
  port: 8082

spring:
  liquibase:
    enabled: true
    contexts: test
  jpa:
    properties:
      hibernate.show_sql: false
      hibernate:format_sql: false
    open-in-view: false
    hibernate.ddl-auto: none
  datasource:
    #  Note that the hostname, port and database name on url property and username and password properties will be ignored
    #  and it will be used default container values
    url: jdbc:postgresql://localhost:5432/note?user=nikita&password=91823God&currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: nikita
    password: 91823God
    hikari:
      schema: public